stages:
    - build
    - static_analysis
    - test

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
        - if: $CI_COMMIT_BRANCH == 'main'
        - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api$/

cache:
    paths:
        - vendor/

#JOBS
build_app:
    stage: build
    image:
        name: php:7.4-apache
    before_script:
        - apt-get update
        - apt-get install -y software-properties-common
        - apt-get install -y zip unzip
        - php -r "copy('https://getcomposer.org/download/latest-stable/composer.phar', 'composer.phar');"
    script:
        - php composer.phar install --prefer-dist --no-progress

phpcs:
    stage: static_analysis
    script:
        - ls -la *
        - php vendor/bin/phpcs --standard=PSR12 src/

phpstan:
    stage: static_analysis
    script:
        - php vendor/bin/phpstan analyse -c phpstan.neon

test:
    stage: test
    image: php:7.3
    script:
        - php vendor/bin/phpunit