stages:
    - build
    - static_analysis
    - test

workflow:
    rules:
        - if: $CI_MERGE_REQUEST_ID
        - if: $CI_COMMIT_BRANCH == 'main'
        - if: $CI_PIPELINE_SOURCE =~ /^trigger|pipeline|web|api$/

cache:
    paths:
        - vendor/

#JOBS
build_app:
    stage: build
    image:
        name: php:7.4-apache
    script:
        - apt-get update
        - apt-get install -y software-properties-common
        - apt-get install -y zip unzip
        - php -r "copy('https://getcomposer.org/download/latest-stable/composer.phar', 'composer.phar');"
        - php composer.phar install --prefer-dist --no-progress

phpcs:
    stage: static_analysis
    image:
        name: cytopia/phpcs
        entrypoint: ["/bin/ash", "-c"]
    script:
        - phpcs *.php

phpstan:
    stage: static_analysis
    image:
        name: phpstan/phpstan
        entrypoint: ["/bin/ash", "-c"]
    script:
        - phpstan analyse --no-interaction --ansi --error-format=table --no-progress --level 5 src

test:
    stage: test
    image: php:7.3
    script:
        - php vendor/bin/phpunit
